<?php
class K8Acf
{
	public $f_id;

	function __construct(){
		$this->f_id = array(
			'5dde6878b95b0'
		);
		add_action( 'acf/init', array( $this, 'anbieter_cf' ) );
		add_action( 'acf/init', array( $this, 'user_info' ) );
		add_action( 'acf/init', array( $this, 'faq' ) );
		add_action( 'acf/init', array( $this, 'slider' ) );
		add_action( 'acf/init', array( $this, 'iframesAsync' ) );

		add_action( 'acf/init', array( $this, 'howto' ) );

		add_action( 'acf/init', array( $this, 'amp' ) );

		add_action( 'acf/init', array( $this, 'popup' ) );

		add_action( 'acf/init', array( $this, 'organization' ) );

		add_action( 'acf/init', array( $this, 'passgen' ) );

		add_action( 'acf/init', array( $this, 'widget' ) );

	}
	public function anbieter_cf(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5c83071429237',
				'title' => 'VPN Details',
				'fields' => array(
					array(
						'key' => 'field_5d2f189bad5fc',
						'label' => 'VPN Id',
						'name' => 'k8_acf_vpnid',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d5405265be1c',
						'label' => 'Connections per account',
						'name' => 'k8_acf_vpndet_conn',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => '1',
							2 => '2',
							3 => '3',
							4 => '4',
							5 => '5',
							6 => '6',
							7 => '7',
							8 => '8',
							9 => '9',
							10 => '10',
							30 => '30',
							0 => __( 'unlimitiert', 'k8lang_domain' ),
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5d550ada4ea45',
						'label' => 'Currency',
						'name' => 'k8_acf_vpndet_curr',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'usd' => 'USD',
							'eur' => 'EUR',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5d550b7b4ea46',
						'label' => 'Duration 1',
						'name' => 'k8_acf_vpndet_durr1',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d550bd34ea47',
						'label' => 'Price 1',
						'name' => 'k8_acf_vpndet_prc1',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d550c164ea48',
						'label' => 'Duration 2',
						'name' => 'k8_acf_vpndet_durr2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d550c214ea49',
						'label' => 'Price 2',
						'name' => 'k8_acf_vpndet_prc2',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d550c344ea4a',
						'label' => 'Duration 3',
						'name' => 'k8_acf_vpndet_durr3',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d550c454ea4b',
						'label' => 'Price 3',
						'name' => 'k8_acf_vpndet_prc3',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d550c524ea4c',
						'label' => 'Duration 4',
						'name' => 'k8_acf_vpndet_durr4',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d550c5c4ea4d',
						'label' => 'Price 4',
						'name' => 'k8_acf_vpndet_prc4',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d550d2e4ea4e',
						'label' => __( 'Testmöglichkeiten', 'k8lang_domain' ),
						'name' => 'k8_acf_vpndet_trialz',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '75',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'free' => __( 'Kostenloser Tarif verfügbar', 'k8lang_domain' ),
							'back' => __( 'Geld-Zurück-Garantie', 'k8lang_domain' ),
							'trial' => __( 'Limitierte kostenfreie Testzeit (Ohne Zahlung)', 'k8lang_domain' ),
							'spec' => __( 'Rabattierte Testzeit (Sonderpreis für begrenzte Zeit)', 'k8lang_domain' ),
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5d82edce9cd47',
						'label' => 'Average price per month',
						'name' => 'k8_acf_vpndet_avg',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'This price calculates automatically',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d7f199971aeb',
						'label' => 'Videoplattformen (Streaming)',
						'name' => 'k8_acf_vpndet_vid',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'net' => __( 'Netflix (DE)', 'k8lang_domain' ),
							'amaz' => __( 'Amazon Video (DE)', 'k8lang_domain' ),
							'dazn' => __( 'DAZN (DE)', 'k8lang_domain' ),
							'sky' => __( 'Sky (DE)', 'k8lang_domain' ),
							'euro' => __( 'Eurosport (DE)', 'k8lang_domain' ),
							'max' => __( 'Maxdome', 'k8lang_domain' ),
							'zat' => __( 'zattoo (CH)', 'k8lang_domain' ),
							'wai' => __( 'Waipu', 'k8lang_domain' ),
							'joy' => __( 'JOYN', 'k8lang_domain' ),
							'tv' => __( 'TVNow', 'k8lang_domain' ),
							'ard' => __( 'ARD (DE)', 'k8lang_domain' ),
							'zdf' => __( 'ZDF (DE)', 'k8lang_domain' ),
							'br' => __( 'BR DE)', 'k8lang_domain' ),
							'n24' => __( 'N24 (DE)', 'k8lang_domain' ),
							'mdr' => __( 'MDR (DE)', 'k8lang_domain' ),
							'rbb' => __( 'rbb (DE)', 'k8lang_domain' ),
							'wdr' => __( 'WDR (DE)', 'k8lang_domain' ),
							'art' => __( 'Arte DE)', 'k8lang_domain' ),
							'sat3' => __( '3Sat (DE)', 'k8lang_domain' ),
							'pro7' => __( 'Pro7 (DE)', 'k8lang_domain' ),
							'sat1' => __( 'Sat1 (DE)', 'k8lang_domain' ),
							'kab1' => __( 'Kabel1 (DE)', 'k8lang_domain' ),
							'disn_de' => __( 'Disney+ (DE)', 'k8lang_domain' ),
							'magtv_de' => __( 'MagentaTV (DE)', 'k8lang_domain' ),
							'orf' => __( 'ORF (AT)', 'k8lang_domain' ),
							'srf' => __( 'SRF (CH)', 'k8lang_domain' ),
							'serv' => __( 'Servus TV (DE, AT, CH)', 'k8lang_domain' ),
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => $this->f_id[0],
						'label' => 'Videoplattformen International (Streaming)',
						'name' => 'k8_acf_vpndet_vid_int',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'disney_plus_us' => __( 'Disney+ (US)', 'k8lang_domain' ),
							'hulu_us' => __( 'Hulu (US)', 'k8lang_domain' ),
							'amazon_prime_us' => __( 'Amazon Prime Video (US)', 'k8lang_domain' ),
							'netflix_us' => __( 'Netflix (US)', 'k8lang_domain' ),
							'apple_tv_us' => __( 'Apple TV (US)', 'k8lang_domain' ),
							'watch_espn_us' => __( 'Watch ESPN (US)', 'k8lang_domain' ),
							'channel_4_us' => __( 'Channel 4 (US)', 'k8lang_domain' ),
							'nfl_gamepass_us' => __( 'NFL Gamepass (US)', 'k8lang_domain' ),
							'mlb_us' => __( 'MLB.tv (US)', 'k8lang_domain' ),
							'abc_us' => __( 'abc (US)', 'k8lang_domain' ),
							'cbs_us' => __( 'CBS (US)', 'k8lang_domain' ),
							'fox_us' => __( 'FOX (US)', 'k8lang_domain' ),
							'nbc_us' => __( 'NBC (US)', 'k8lang_domain' ),
							'showtime_us' => __( 'Showtime (US)', 'k8lang_domain' ),
							'flix_us' => __( 'FLIX (US)', 'k8lang_domain' ),
							'epix_us' => __( 'epix (US)', 'k8lang_domain' ),
							'hbo_now_us' => __( 'HBO Now (US)', 'k8lang_domain' ),
							'itv_uk' => __( 'ITV (UK)', 'k8lang_domain' ),
							'eurosport_uk' => __( 'Eurosport (UK)', 'k8lang_domain' ),
							'sky_uk' => __( 'Sky (UK)', 'k8lang_domain' ),
							'bbc_uk' => __( 'BBC iPlayer (UK)', 'k8lang_domain' ),
							'sky_news_uk' => __( 'Sky News (UK)', 'k8lang_domain' ),
							'bloomberg_uk' => __( 'Bloomberg (UK)', 'k8lang_domain' ),
							'bt_sport' => __( 'BT Sport (UK)', 'k8lang_domain' ),
							'channel_4_uk' => __( 'Channel 4 (UK)', 'k8lang_domain' ),
							'sky_go_it' => __( 'Sky Go (IT)', 'k8lang_domain' ),
							'youtube' => __( 'YouTube', 'k8lang_domain' ),
							'spotify' => __( 'Spotify', 'k8lang_domain' ),
							'starz_us' => __( 'starz (US)', 'k8lang_domain' ),
							'hustlertv_us' => __( 'hustlerTV (US)', 'k8lang_domain' ),
							'penthousetv_us' => __( 'PenthouseTV (US)', 'k8lang_domain' ),
							'playboytv_us' => __( 'PlayboyTV (US)', 'k8lang_domain' ),
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5dcc79d3b36d2',
						'label' => 'Download speed',
						'name' => 'k8_acf_vpndet_down',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'kbps',
						'min' => 1,
						'max' => 40000000,
						'step' => '',
					),
					array(
						'key' => 'field_5dcc7a39b36d3',
						'label' => 'Upload speed',
						'name' => 'k8_acf_vpndet_up',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'kbps',
						'min' => 1,
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5dcc7a5cb36d4',
						'label' => 'Ping',
						'name' => 'k8_acf_vpndet_ping',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'ms',
						'min' => 0,
						'max' => 999,
						'step' => '',
					),
					array(
						'key' => 'field_5dcc7a8fb36d5',
						'label' => 'Jitter',
						'name' => 'k8_acf_vpndet_jitter',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'ms',
						'min' => 0,
						'max' => 999,
						'step' => '',
					),
					array(
						'key' => 'field_5dcc7e879001a',
						'label' => 'Country of Measurement',
						'name' => 'k8_acf_vpndet_meas',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Germany' => __( 'Deutschland', 'k8lang_domain' ),
							'USA' => __( 'USA', 'k8lang_domain' ),
							'UK' => __( 'Großbritannien', 'k8lang_domain' ),
							'Russia' => __( 'Russland', 'k8lang_domain' ),
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'Germany',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5de6cb6e05e4f',
						'label' => 'Billing',
						'name' => 'k8_acf_verrechnung',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'belize' => __( 'Belize', 'k8lang_domain' ),
							'bv-islands' =>  __( 'BV.Islands', 'k8lang_domain' ),
							'cayman-islands' => __( 'Cayman Islands', 'k8lang_domain' ),
							'commonwealth-of-dominic' => __( 'Commonwealth of Dominic', 'k8lang_domain' ),
							'deutschland' => __( 'Deutschland', 'k8lang_domain' ),
							'finnland' => __( 'Finnland', 'k8lang_domain' ),
							'frankreich' => __( 'Frankreich', 'k8lang_domain' ),
							'grossbritannien' => __( 'Großbritannien', 'k8lang_domain' ),
							'hongkong' => __( 'HongKong', 'k8lang_domain' ),
							'indien' => __( 'Indien', 'k8lang_domain' ),
							'irland' => __( 'Irland', 'k8lang_domain' ),
							'israel' => __( 'Israel', 'k8lang_domain' ),
							'kanada' => __( 'Kanada', 'k8lang_domain' ),
							'niederlande' => __( 'Niederlande', 'k8lang_domain' ),
							'nord-zypern' => __( 'Nord-Zypern', 'k8lang_domain' ),
							'panama' => __( 'Panama', 'k8lang_domain' ),
							'rumaenien' => __( 'Rumänien', 'k8lang_domain' ),
							'russland' => __( 'Russland', 'k8lang_domain' ),
							'san-marino' => __( 'San Marino', 'k8lang_domain' ),
							'schweden' => __( 'Schweden', 'k8lang_domain' ),
							'schweiz' => __( 'Schweiz', 'k8lang_domain' ),
							'seychellen' => __( 'Seychellen', 'k8lang_domain' ),
							'tschechien' => __( 'Tschechien', 'k8lang_domain' ),
							'usa' => __( 'USA', 'k8lang_domain' ),
							'zypern' => __( 'Zypern', 'k8lang_domain' )
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5de796009f608',
						'label' => 'Local legislation affects',
						'name' => 'k8_acf_local',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5de7cc1138e3e',
						'label' => 'Prevent monitoring',
						'name' => 'k8_acf_prev_monit',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5de7cc5938e3f',
						'label' => 'Prevent targeted monitoring',
						'name' => 'k8_acf_prev_monit2',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5de7ca9c13057',
						'label' => 'Language in Customer Service',
						'name' => 'k8_acf_lang_kund',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'deutsch' => __( 'Deutsch', 'k8lang_domain' ),
							'englisch' => __( 'Englisch', 'k8lang_domain' ),
							'franzoesisch' => __( 'Französisch', 'k8lang_domain' ),
							'russisch' => __( 'Russisch', 'k8lang_domain' ),
							'schwedisch' => __( 'Schwedisch', 'k8lang_domain' ),
							'spanisch' => __( 'Spanisch', 'k8lang_domain' ),
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_60e80d8c4888c',
						'label' => 'Trust Level',
						'name' => 'k8_acf_trust_level',
						'type' => 'range',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'min' => 0,
						'max' => 100,
						'step' => '',
						'prepend' => '',
						'append' => '',
					),
				), # END OF fields Array
				'location' => array(
					array(
						array(
							'param' => 'post_category',
							'operator' => '==',
							'value' => 'category:anbieter',
						),
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
					),
					array(
						array(
							'param' => 'post_category',
							'operator' => '==',
							'value' => 'category:vpn-anbieter',
						),
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'acf_after_title',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'excerpt',
					1 => 'discussion',
					2 => 'comments',
					3 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
			));
		endif;
	}

	#USER INFO ( IMAGE with Description )
	public function user_info(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5d1dc59e5ab2a',
				'title' => 'User info',
				'fields' => array(
					array(
						'key' => 'field_5d2585c55287a',
						'label' => 'User Photo',
						'name' => 'k8_acf_u_ph',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5d2585f95287b',
						'label' => 'User Info',
						'name' => 'k8_acf_u_desc',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'user_role',
							'operator' => '==',
							'value' => 'all',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}

	#FAQ Shortcode
	public function faq(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5da9a88aa4335',
				'title' => 'FAQ',
				'fields' => array(
					array(
						'key' => 'field_5da9a89fb2b69',
						'label' => 'Question&Answer',
						'name' => 'k8_acf_faq',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_5da9a8f6b2b6a',
								'label' => 'Question',
								'name' => 'quest',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5da9a90db2b6b',
								'label' => 'Answer',
								'name' => 'ans',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
					),
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'page',
						),
					),
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'affcoups_coupon',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}

	# Slider Shortcode
	public function slider(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5d6798ce9ae56',
				'title' => 'Slider',
				'fields' => array(
					array(
						'key' => 'field_5d6798f45d94b',
						'label' => 'Slider',
						'name' => 'k8_acf_dwn_slider',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_5d67991a5d94c',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'id',
								'preview_size' => 'large',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5da424770271f',
								'label' => 'text',
								'name' => 'text',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
						// array(
						// 	'param' => 'post_category',
						// 	'operator' => '==',
						// 	'value' => 'category:anbieter',
						// ),
					),
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'downloads',
						),
					),
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'page',
						),
					),
					// array(
					// 	array(
					// 		'param' => 'post_type',
					// 		'operator' => '==',
					// 		'value' => 'post',
					// 	),
					// 	array(
					// 		'param' => 'post_category',
					// 		'operator' => '==',
					// 		'value' => 'category:vpn-anbieter',
					// 	),
					// ),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}

	#Iframes Async Load
	public function iframesAsync(){
		acf_add_local_field_group(array(
			'key' => 'group_5e0a290ab20e5',
			'title' => 'Iframes Async Load',
			'fields' => array(
				array(
					'key' => 'field_5e0a2925377d2',
					'label' => 'Url of short affiliate linlk',
					'name' => 'k8_acf_ifr_url',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_5e0a295b377d3',
							'label' => 'Url',
							'name' => 'url',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
					),
				),
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'page',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
		));
	}


	#HOWTO
	public function howto(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5df4b76c17916',
				'title' => 'HowTo',
				'fields' => array(
					array(
						'key' => 'field_5e26f08d49f08',
						'label' => 'Steps',
						'name' => 'k8_acf_howto_stp',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_5e26fd1ca9f71',
								'label' => 'Number',
								'name' => 'num',
								'type' => 'number',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '5',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_5e26f0bf49f09',
								'label' => 'Head',
								'name' => 'head',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5e26f0dc49f0a',
								'label' => 'Text',
								'name' => 'txt',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_5e26f0f549f0b',
								'label' => 'Image',
								'name' => 'img',
								'type' => 'image',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '20',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'id',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
					),
					array(
						'key' => 'field_5e297d2bb5f65',
						'label' => 'Supply',
						'name' => 'k8_acf_howto_supply',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_5e297d45b5f66',
								'label' => 'Text',
								'name' => 'txt',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_5e297d62b5f67',
						'label' => 'Tool',
						'name' => 'k8_acf_howto_tool',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_5e297d73b5f68',
								'label' => 'Text',
								'name' => 'txt',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'k8pt_howto',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}

	#AMP support
	public function amp(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5e4564086c382',
				'title' => 'Site Options',
				'fields' => array(
					array(
						'key' => 'field_5e4566a16a884',
						'label' => 'AMP',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e4566bc6a885',
						'label' => 'Enabled',
						'name' => 'k8_optz_amp',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5eec9bc8dfda6',
						'label' => 'Categories where works',
						'name' => 'k8_optz_amp_cat',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5e4566bc6a885',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'category',
						'field_type' => 'checkbox',
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'multiple' => 0,
						'allow_null' => 0,
					),
					array(
						'key' => 'field_5e456750b9f98',
						'label' => 'Google Analitics ID',
						'name' => 'k8_optz_amp_ga',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5e4566bc6a885',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ece4797eaf5e',
						'label' => 'Top Menu Name',
						'name' => 'k8_optz_amp_mn',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5e4566bc6a885',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),

					#Analitics
					array(
						'key' => 'field_5ee89ba62b3b1',
						'label' => 'Google Analitics',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ee896656e45a',
						'label' => 'Enable Google Analitics',
						'name' => 'm5_opt_ga',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ee896fc6e45b',
						'label' => 'Tracking code',
						'name' => 'm5_opt_ga_tr',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ee896656e45a',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_5ee8975f8f586',
						'label' => 'Affiliate Links Tracking',
						'name' => 'm5_opt_ga_aff',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ee896656e45a',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_5ee897a78f587',
								'label' => 'Affiliate link',
								'name' => 'aff_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),

					#Fast Affiliate links
					array(
						'key' => 'field_5ef606e95afaa',
						'label' => 'Fast Affiliates',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ef606a05afa9',
						'label' => 'Fast affiliates use/not',
						'name' => 'm5_opt_fast_tf',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ef6061111629',
						'label' => 'Fast affiliates',
						'name' => 'm5_opt_fast',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ef606a05afa9',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef6078fb9cf7',
								'label' => 'Affiliate Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ef6064c1162a',
								'label' => 'Affiliate Logo',
								'name' => 'logo',
								'type' => 'image',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'id',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5ef6066f1162b',
								'label' => 'Affiliate Url',
								'name' => 'url',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_6085dbc5515e0',
						'label' => 'Beste VPN',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_6085dbf6515e1',
						'label' => 'Use / Not',
						'name' => 'beste_mob_use__not',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							0 => 'No',
							1 => 'Yes',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 0,
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_6085dc4c47c68',
						'label' => 'Title',
						'name' => 'beste_mob_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6085dbf6515e1',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6085dc7247c69',
						'label' => 'Url',
						'name' => 'beste_mob_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6085dbf6515e1',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'options_page',
							'operator' => '==',
							'value' => 'acf-options',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}

	#popup
	public function popup(){

		if( function_exists('acf_add_local_field_group') ):
			// echo 'Herre!';
			acf_add_local_field_group(array(
				'key' => 'group_5ece4797eaf5e',
				'title' => 'Popups',
				'fields' => array(
					array(
						'key' => 'field_5f0e8be7d015e',
						'label' => 'How many times dont show before show',
						'name' => 'm5_acf_pop_times',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 1,
						'max' => 9999,
						'step' => '',
					),
					array(
						'key' => 'field_5f0e8bfa19d88',
						'label' => 'Date until end of timer',
						'name' => 'm5_acf_pop_date_to',
						'type' => 'date_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'Y-m-d',
						'return_format' => 'Y-m-d',
						'first_day' => 1,
					),
					array(
						'key' => 'field_606357651f6d1',
						'label' => 'Delay in seconds before popup appears',
						'name' => 'm5_acf_pop_delay',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							2000 => '2',
							5000 => '5',
							7000 => '7',
							10000 => '10',
							20000 => '20',
							30000 => '30',
							60000 => '60',
							90000 => '90',
						),
						'default_value' => 2,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_5f0e8c116659e',
						'label' => 'Logo image',
						'name' => 'm5_acf_pop_logo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5f0e8c28805ad',
						'label' => 'Button\'s Url',
						'name' => 'm5_acf_pop_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f8ece4a10299',
						'label' => 'Type of popup',
						'name' => 'm5_acf_pop_type',
						'type' => 'radio',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'small' => 'Affiliate\'s website opens in new small browser\'s tab, then it dissapears after a while',
							'full' => 'Affiliate\'s website opens in the same browser\'s tab and in new tab opens the same page',
							'usual' => 'Typical popup, which appears without any tricks',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'small',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'm5pt_popup',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));

		endif;
	}

	#Organization Schema
	public function organization(){

		if( function_exists('acf_add_local_field_group') ){
			acf_add_local_field_group(array(
				'key' => 'group_5f2bbd83b5c1d',
				'title' => 'Organization',
				'fields' => array(
					array(
						'key' => 'field_5f2bbd89c87f1',
						'label' => 'Organization schema data',
						'name' => 'k8_schema_org_data',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5f2bbda3c87f2',
								'label' => 'Organization info',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array(
								'key' => 'field_5f2bef48b95c6',
								'label' => 'Logo',
								'name' => 'logo',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5f2be299293cb',
								'label' => 'Organization name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f2be2d9293cd',
								'label' => 'Legal name',
								'name' => 'legal_name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f2be4403c9e9',
								'label' => 'Founding year',
								'name' => 'founding_year',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_5f2be4843c9eb',
								'label' => 'Founder name',
								'name' => 'founder_name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f2bbdb7c87f3',
								'label' => 'Social links',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array(
								'key' => 'field_5f2be243c1607',
								'label' => 'Social links',
								'name' => 'k8_schema_social_links',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_5f2be262c1608',
										'label' => 'Url',
										'name' => 'url',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
									),
								),
							),
							array(
								'key' => 'field_5f2bbdd1c87f4',
								'label' => 'Contact info',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array(
								'key' => 'field_5f2be4843c9ea',
								'label' => 'Address region',
								'name' => 'address_region',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f2beccc31b4e',
								'label' => 'Address country',
								'name' => 'address_country',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f2becda31b4f',
								'label' => 'Contact Type',
								'name' => 'contact_type',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f2bede131b50',
								'label' => 'Telephone',
								'name' => 'phone',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5f2bedf831b51',
								'label' => 'Email',
								'name' => 'email',
								'type' => 'email',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'options_page',
							'operator' => '==',
							'value' => 'acf-options',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		}
	}

	#Template for password generator template
	public function passgen(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5f9a9c0043121',
				'title' => 'Password Generator Template',
				'fields' => array(
					array(
						'key' => 'field_5f9a9c8614d6f',
						'label' => 'Message',
						'name' => 'pg_message',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Password copied',
						'placeholder' => 'Password copied',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9a9cc714d70',
						'label' => 'Top text',
						'name' => 'pg_top_text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '<h1>Generate a secure password</h1>
			<p>Use this free Password Generator to generate very safe passwords that are hard to crack or guess.</p>',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5f9a9fb41113b',
						'label' => 'Tab 1',
						'name' => 'pg_tab_1',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Easy to remember',
						'placeholder' => 'Easy to remember',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9a9fd61113c',
						'label' => 'Tab 2',
						'name' => 'pg_tab_2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Highly secure',
						'placeholder' => 'Highly secure',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9aa1a3b1fcc',
						'label' => 'Easy',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5f9aa357c09f0',
						'label' => 'Label 1',
						'name' => 'pg_easy_label_1',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Length',
						'placeholder' => 'Length',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9aa39ec09f1',
						'label' => 'Label 2',
						'name' => 'pg_easy_label_2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Is there a word that is special to you? (eg. dog\'s/cat\'s name)',
						'placeholder' => 'Is there a word that is special to you? (eg. dog\'s/cat\'s name)',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9aa3aac09f2',
						'label' => 'Error 2',
						'name' => 'pg_easy_error_2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Please enter your special noun',
						'placeholder' => 'Please enter your special noun',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9aa3dac09f4',
						'label' => 'Label 3',
						'name' => 'pg_easy_label_3',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Adjective characterizing word (eg. white, cute)',
						'placeholder' => 'Adjective characterizing word (eg. white, cute)',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ac71865d66',
						'label' => 'Error 3',
						'name' => 'pg_easy_error_3',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Please enter an adjective',
						'placeholder' => 'Please enter an adjective',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ac7805c3b4',
						'label' => 'Label 4',
						'name' => 'pg_easy_label_4',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Enter your lucky number',
						'placeholder' => 'Enter your lucky number',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ac79d5c3b5',
						'label' => 'Error 4',
						'name' => 'pg_easy_error_4',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Please enter your lucky number',
						'placeholder' => 'Please enter your lucky number',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ac7dc5bafe',
						'label' => 'Label 5',
						'name' => 'pg_easy_label_5',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Include Uppercase Characters ( ABCDEF... )',
						'placeholder' => 'Include Uppercase Characters ( ABCDEF... )',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ac7f25baff',
						'label' => 'Label 6',
						'name' => 'pg_easy_label_6',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Include Symbols ( {}[]()/\\\'"$#~+-,;:. )',
						'placeholder' => 'Include Symbols ( {}[]()/\\\'"$#~+-,;:. )',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ace6127fe7',
						'label' => 'Label 7',
						'name' => 'pg_easy_label_7',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'If you forget your password, you can re-enter the same parameters, to restore it.',
						'placeholder' => 'If you forget your password, you can re-enter the same parameters, to restore it.',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ad0b04729a',
						'label' => 'Secure',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5f9ad0be4729b',
						'label' => 'Label 1',
						'name' => 'pg_sec_label_1',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Advanced options',
						'placeholder' => 'Advanced options',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ad11c4729c',
						'label' => 'Label 2',
						'name' => 'pg_sec_label_2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Length',
						'placeholder' => 'Length',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ad1314729d',
						'label' => 'Label 3',
						'name' => 'pg_sec_label_3',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Include Numbers ( 12345 )',
						'placeholder' => 'Include Numbers ( 12345 )',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ad13d4729e',
						'label' => 'Label 4',
						'name' => 'pg_sec_label_4',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Include Lowercase Characters ( abcdef... )',
						'placeholder' => 'Include Lowercase Characters ( abcdef... )',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ad14d4729f',
						'label' => 'Label 5',
						'name' => 'pg_sec_label_5',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Include Uppercase Characters ( ABCDEF... )',
						'placeholder' => 'Include Uppercase Characters ( ABCDEF... )',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ad165472a0',
						'label' => 'Label 6',
						'name' => 'pg_sec_label_6',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Include Symbols ( {}[]()/\\\'"$#~+-,;:. )',
						'placeholder' => 'Include Symbols ( {}[]()/\\\'"$#~+-,;:. )',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ad172472a1',
						'label' => 'Label 7',
						'name' => 'pg_sec_label_7',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Include Spaces',
						'placeholder' => 'Include Spaces',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5f9ad199a0b49',
						'label' => 'Notice',
						'name' => 'pg_sec_notice',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Note: All the created passwords are only accessible on your local computer and we do not store any results or information that you provide. It is your browser that generates your secure password randomly by using JavaScript.
			There is no transfer of passwords over the Internet. The benefit of this strategy is that the password created resides on your device and is not distributed to or from an external server.',
						'placeholder' => 'Note: All the created passwords are only accessible on your local computer and we do not store any results or information that you provide. It is your browser that generates your secure password randomly by using JavaScript. There is no transfer of passwords over the Internet. The benefit of this strategy is that the password created resides on your device and is not distributed to or from an external server.',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => 'br',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'page_template',
							'operator' => '==',
							'value' => 'k8tpl-passgen.php',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'acf_after_title',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));

			endif;
	}


	#Custom widget top rated products
	public function widget(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_606eda0d57df7',
				'title' => 'Top Rated List',
				'fields' => array(
					array(
						'key' => 'field_606eda4551e46',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_606f15a0c73da',
						'label' => 'Links',
						'name' => 'links',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'block',
						'button_label' => '',
						'sub_fields' => array(
							array(
								'key' => 'field_606f15f6c73db',
								'label' => 'Logo',
								'name' => 'logo',
								'type' => 'image',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'id',
								'preview_size' => 'pt_view_100x100',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_606f16c0c73df',
								'label' => 'Score',
								'name' => 'score',
								'type' => 'number',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => 10,
								'step' => '0.1',
							),
							array(
								'key' => 'field_606f1628c73dc',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_606f1639c73dd',
								'label' => 'Url to page review',
								'name' => 'url_to_page',
								'type' => 'link',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
							array(
								'key' => 'field_606f1675c73de',
								'label' => 'Affiliate link',
								'name' => 'affiliate_link',
								'type' => 'link',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
						),
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'widget',
							'operator' => '==',
							'value' => 'm5top-wdg',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}
}
new K8Acf();