<?php
class K8Acf
{
	public $k8_arrr;
	function __construct(){
		$this->k8_arrr = array(
			'https://gratisvpn.de',
			'https://vpntester.ru',
			'https://vpnanbietervergleich.de'
		);
		if( in_array(get_site_url(), $this->k8_arrr) ){
			add_action( 'acf/init', array( $this, 'anbieter_cf' ) );
		}
	}
	public function anbieter_cf(){
		if( function_exists('acf_add_local_field_group') ):

			acf_add_local_field_group(array(
				'key' => 'group_5c83071429237',
				'title' => 'VPN Details',
				'fields' => array(
					array(
						'key' => 'field_5d2f189bad5fc',
						'label' => 'VPN Id',
						'name' => 'k8_acf_vpnid',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d5405265be1c',
						'label' => 'Connections per account',
						'name' => 'k8_acf_vpndet_conn',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => '1',
							2 => '2',
							3 => '3',
							4 => '4',
							5 => '5',
							6 => '6',
							7 => '7',
							8 => '8',
							9 => '9',
							10 => '10',
							0 => 'unlimitiert',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5d550ada4ea45',
						'label' => 'Currency',
						'name' => 'k8_acf_vpndet_curr',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'usd' => 'USD',
							'eur' => 'EUR',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5d550b7b4ea46',
						'label' => 'Duration 1',
						'name' => 'k8_acf_vpndet_durr1',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d550bd34ea47',
						'label' => 'Price 1',
						'name' => 'k8_acf_vpndet_prc1',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d550c164ea48',
						'label' => 'Duration 2',
						'name' => 'k8_acf_vpndet_durr2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d550c214ea49',
						'label' => 'Price 2',
						'name' => 'k8_acf_vpndet_prc2',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d550c344ea4a',
						'label' => 'Duration 3',
						'name' => 'k8_acf_vpndet_durr3',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d550c454ea4b',
						'label' => 'Price 3',
						'name' => 'k8_acf_vpndet_prc3',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d550c524ea4c',
						'label' => 'Duration 4',
						'name' => 'k8_acf_vpndet_durr4',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5d550c5c4ea4d',
						'label' => 'Price 4',
						'name' => 'k8_acf_vpndet_prc4',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d550d2e4ea4e',
						'label' => 'Testmöglichkeiten',
						'name' => 'k8_acf_vpndet_trialz',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '75',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'free' => 'Kostenloser Tarif verfügbar',
							'back' => 'Geld-Zurück-Garantie',
							'trial' => 'Limitierte kostenfreie Testzeit (Ohne Zahlung)',
							'spec' => 'Rabattierte Testzeit (Sonderpreis für begrenzte Zeit)',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5d82edce9cd47',
						'label' => 'Average price per month',
						'name' => 'k8_acf_vpndet_avg',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'This price calculates automatically',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5d7f199971aeb',
						'label' => 'Videoplattformen (Streaming)',
						'name' => 'k8_acf_vpndet_vid',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'net' => 'Netflix (DE)',
							'amaz' => 'Amazon Video (DE)',
							'dazn' => 'DAZN (DE)',
							'sky' => 'Sky (DE)',
							'euro' => 'Eurosport (DE)',
							'max' => 'Maxdome',
							'zat' => 'zattoo (CH)',
							'wai' => 'Waipu',
							'joy' => 'JOYN',
							'tv' => 'TVNow',
							'max2' => 'maxdome',
							'ard' => 'ARD (DE)',
							'zdf' => 'ZDF (DE)',
							'br' => 'BR DE)',
							'n24' => 'N24 (DE)',
							'mdr' => 'MDR (DE)',
							'rbb' => 'rbb (DE)',
							'wdr' => 'WDR (DE)',
							'art' => 'Arte DE)',
							'sat3' => '3Sat (DE)',
							'pro7' => 'Pro7 (DE)',
							'sat1' => 'Sat1 (DE)',
							'kab1' => 'Kabel1 (DE)',
							'orf' => 'ORF (AT)',
							'srf' => 'SRF (CH)',
							'serv' => 'Servus TV (DE, AT, CH)',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5dcc79d3b36d2',
						'label' => 'Download speed',
						'name' => 'k8_acf_vpndet_down',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'kbps',
						'min' => 1,
						'max' => 400000,
						'step' => '',
					),
					array(
						'key' => 'field_5dcc7a39b36d3',
						'label' => 'Upload speed',
						'name' => 'k8_acf_vpndet_up',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'kbps',
						'min' => 1,
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5dcc7a5cb36d4',
						'label' => 'Ping',
						'name' => 'k8_acf_vpndet_ping',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'ms',
						'min' => 1,
						'max' => 999,
						'step' => '',
					),
					array(
						'key' => 'field_5dcc7a8fb36d5',
						'label' => 'Jitter',
						'name' => 'k8_acf_vpndet_jitter',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'ms',
						'min' => 1,
						'max' => 999,
						'step' => '',
					),
					array(
						'key' => 'field_5dcc7e879001a',
						'label' => 'Country of Measurement',
						'name' => 'k8_acf_vpndet_meas',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Germany' => 'Deutschland',
							'USA' => 'USA',
							'UK' => 'Großbritannien',
							'Russia' => 'Russland',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'Germany',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_category',
							'operator' => '==',
							'value' => 'category:anbieter',
						),
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'acf_after_title',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'excerpt',
					1 => 'discussion',
					2 => 'comments',
					3 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
			));

		endif;
	}
}
new K8Acf();