<?php
class K8AcfRouter
{
	function __construct()
	{
		add_action( 'acf/init', array( $this, 'router' ) );
	}

	public function router(){
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5e99b45dba028',
				'title' => 'Router',
				'fields' => array(
					array(
						'key' => 'field_5e99b4c8222bf',
						'label' => 'ID',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e99b4e5222c0',
						'label' => 'ROUTERID',
						'name' => 'm5_rou_id',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99b67c222c1',
						'label' => 'Product Name',
						'name' => 'm5_rou_id_name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99b734222c2',
						'label' => 'Model Vendor-ID',
						'name' => 'm5_rou_id_venid',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99b752222c3',
						'label' => 'Model Year',
						'name' => 'm5_rou_id_year',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99b86a6a20f',
						'label' => 'Product Image',
						'name' => 'm5_rou_id_prod_img',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'wcsquare',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5e99b8be6a210',
						'label' => 'Images various',
						'name' => 'm5_rou_id_var_img',
						'type' => 'gallery',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'medium',
						'insert' => 'append',
						'library' => 'all',
						'min' => '',
						'max' => '',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5e99b8ec6a211',
						'label' => 'Product Link',
						'name' => 'm5_rou_id_prod_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99b91b6a212',
						'label' => 'Specifications Link',
						'name' => 'm5_rou_id_spec_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99b9606a213',
						'label' => 'Affiliate Link Text',
						'name' => 'm5_rou_id_aff_link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99b9906a214',
						'label' => 'Affiliate Link',
						'name' => 'm5_rou_id_aff_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99b9ad6a215',
						'label' => 'Shop Link',
						'name' => 'm5_rou_id_shop_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99ba516a216',
						'label' => 'Price',
						'name' => 'm5_rou_id_prc',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99baa76a217',
						'label' => 'Router Group',
						'name' => 'm5_rou_id_rtr_grp',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Wifi/LAN',
							2 => 'Wifi/LAN + Modem',
							3 => 'No Wifo + Modem',
							4 => 'Repeater Wifi',
							5 => 'AccessPoint LAN',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5e99bd3f3aa10',
						'label' => 'Vendor',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e99bd6e3aa11',
						'label' => 'Manufactor',
						'name' => 'm5_rou_vnd_mnf',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'ASUS',
							2 => 'Gl-iNet',
							3 => 'Vilfo',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5e99bdd03aa12',
						'label' => 'Production',
						'name' => 'm5_rou_vnd_prd',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'TW' => 'Taiwan',
							'CN' => 'China',
							'SE' => 'Sweden',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5e99c09b5f1f7',
						'label' => 'Customer Care',
						'name' => 'm5_rou_vnd_cst',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Dealer',
							2 => 'EMail',
							3 => 'Live-Chat',
							4 => 'Tickets',
							5 => 'Website FAQ',
							6 => 'Website Forum',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e99c18993903',
						'label' => 'Language of Customer Care',
						'name' => 'm5_rou_vnd_lng',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Englisch',
							2 => 'German',
							3 => 'Swedisch',
							4 => 'Chinese',
							5 => 'Others',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e99c1fc93904',
						'label' => 'Website',
						'name' => 'm5_rou_vnd_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5e99c8e07e7b3',
						'label' => 'Software',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e99c8fa7e7b4',
						'label' => 'FIRMWARE',
						'name' => 'm5_rou_sft_frm',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'ASUSWRT',
							2 => 'OpenWRT',
							3 => 'DD-WRT',
							4 => 'Tomato',
							5 => 'FritzOS',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5e99c98b7e7b5',
						'label' => 'Flashable',
						'name' => 'm5_rou_sft_flsh',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e99c9b77e7b6',
						'label' => 'Extendable',
						'name' => 'm5_rou_sft_xt',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e99c9c67e7b7',
						'label' => 'Appstore',
						'name' => 'm5_rou_sft_apst',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e99ca0792f27',
						'label' => 'Administration',
						'name' => 'm5_rou_sft_adm',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Web-Interface',
							2 => 'SSH',
							3 => 'App',
							4 => 'Remote Access',
							5 => 'Browser Plugins',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e99ca5292f28',
						'label' => 'Modus',
						'name' => 'm5_rou_sft_mod',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Router',
							2 => 'Repeater',
							3 => 'AccessPoint',
							4 => 'Bridge',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e99ca7d92f29',
						'label' => 'Management',
						'name' => 'm5_rou_sft_mng',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'UPnP',
							2 => 'DLNA',
							3 => 'IGMP',
							4 => 'DHCP',
							5 => 'SNMP',
							6 => 'NTP Client',
							7 => 'DDNS',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e99cb1e088c0',
						'label' => 'Hardware',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e99cb32088c1',
						'label' => 'LED Indicator',
						'name' => 'm5_rou_hrd_ind',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'LAN',
							2 => 'WAN',
							3 => 'WI-FI',
							4 => 'Others',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e99cd9c088c2',
						'label' => 'Flash',
						'name' => 'm5_rou_hrd_fl',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99cdbc088c3',
						'label' => 'RAM',
						'name' => 'm5_rou_hrd_rm',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99cdd2088c4',
						'label' => 'Processor',
						'name' => 'm5_rou_hrd_pr',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99cde6088c5',
						'label' => 'Pocessor Core',
						'name' => 'm5_rou_hrd_cr',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Single',
							2 => 'Double',
							3 => 'Quad-Core',
							4 => 'Octa-Core',
							5 => 'Tri-Core',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5e99ce5c088c6',
						'label' => 'Ports',
						'name' => 'm5_rou_hrd_prts',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'USB 2.0',
							2 => 'USB 3.0',
							3 => 'HDMI',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e99ce94088c7',
						'label' => 'Number USB Ports',
						'name' => 'm5_rou_hrd_num',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99cecb088c8',
						'label' => 'AC Input',
						'name' => 'm5_rou_hrd_ac',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => '110V~240V',
							2 => 'USB',
							3 => 'Bult-in Battery',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e99cf1d088ca',
						'label' => 'Consumption / Watt',
						'name' => 'm5_rou_hrd_cns',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99cf39088cb',
						'label' => 'Antenna ( Extern )',
						'name' => 'm5_rou_hrd_ext',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99cfae088cc',
						'label' => 'Antenna ( Internal )',
						'name' => 'm5_rou_hrd_int',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99d09e088ce',
						'label' => 'Weight',
						'name' => 'm5_rou_hrd_wght',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99d0dc088cf',
						'label' => 'Width',
						'name' => 'm5_rou_hrd_wdth',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99d0f2088d0',
						'label' => 'Lenght',
						'name' => 'm5_rou_hrd_lgth',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e99d105088d1',
						'label' => 'High',
						'name' => 'm5_rou_hrd_hgh',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a02e26061d',
						'label' => 'WAN',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e9a02f56061e',
						'label' => 'WAN Connection',
						'name' => 'm5_rou_wn_cn',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '65',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Ethernet',
							2 => 'PPPoE',
							3 => 'LTE/4G',
							4 => '5G',
							5 => '3G',
							6 => 'USB (Modem)',
							7 => 'xDSL',
							8 => 'Fibre',
							9 => 'Wifi',
							10 => 'PPTP',
							11 => 'L2TP',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a039e0541c',
						'label' => 'WAN type',
						'name' => 'm5_rou_wn_tp',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '35',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Single',
							2 => 'Dual WAN',
							3 => 'LoadBalancing',
							4 => 'BackUp',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a04425f144',
						'label' => 'IP Support',
						'name' => 'm5_rou_wn_sp',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'IPv4',
							2 => 'IPv6',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a04715f145',
						'label' => 'DNS Support',
						'name' => 'm5_rou_wn_dns_supp',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Standard',
							2 => 'DNS over TLS',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5e9a04b15f146',
						'label' => 'Firewall (NAT)',
						'name' => 'm5_rou_wn_fw',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Portforwarding',
							2 => 'DMZ',
							3 => 'Networkfilter',
							4 => 'Static Routes',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a051b5f147',
						'label' => 'DDNS Support',
						'name' => 'm5_rou_wn_ddns',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '10',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a055e5f148',
						'label' => 'DNS-Proxy',
						'name' => 'm5_rou_wn_prx',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '10',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a077b637db',
						'label' => 'Wifi',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e9a07e7637dc',
						'label' => 'Wi-Fi Technology',
						'name' => 'm5_rou_wf_tech',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => '802.11a',
							2 => '802.11b',
							3 => '802.11c',
							4 => '802.11e',
							5 => '802.11f',
							6 => '802.11n',
							7 => '802.11ac',
							8 => '802.11ad',
							9 => '802.11ax',
							10 => '1024QAM',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a08d8ea772',
						'label' => 'Wifi Segment',
						'name' => 'm5_rou_wf_seg',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'N300',
							2 => 'N600',
							3 => 'AC750',
							4 => 'AC1200',
							5 => 'AC2400',
							6 => 'AC3200',
							7 => 'AX750',
							8 => 'AX1200',
							9 => 'AX3000',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a0977fca0e',
						'label' => 'Operating Frequency',
						'name' => 'm5_rou_wf_fqz',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => '2.4GHz',
							2 => '5GHz',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a0ccafca0f',
						'label' => 'WI-Fi max speed',
						'name' => 'm5_rou_wf_m_sp',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '10',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a0cfffca10',
						'label' => 'Extendable Wifi',
						'name' => 'm5_rou_wf_ext',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Mesh',
							2 => 'Repeater',
							3 => 'AccessPoints',
							4 => 'Powerline',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a0d67fca11',
						'label' => 'Encryption Wifi',
						'name' => 'm5_rou_wf_enc',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '55',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'No Encyption',
							2 => 'WPA-PSK',
							3 => 'WPA2-PSK',
							4 => 'WPA3-PSK',
							5 => 'WPA-Enterprise',
							6 => 'WPA2-Enterprise',
							7 => 'WPA3-Enterprise',
							8 => '64-bit WEP',
							9 => '128-bit WEP',
							10 => 'WPS Support',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a0de4fca12',
						'label' => 'Wifi Guest Network',
						'name' => 'm5_rou_wf_guest',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a0dfbfca13',
						'label' => 'Wifi Captive Portal',
						'name' => 'm5_rou_wf_capt',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a0e14fca14',
						'label' => 'Average Wifi Range',
						'name' => 'm5_rou_wf_rng',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a1c5a72f60',
						'label' => 'Switch',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e9a1c6f72f61',
						'label' => 'Network Ports',
						'name' => 'm5_rou_sw_net',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'LAN',
							2 => 'WAN',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a1ce472f62',
						'label' => 'LAN Ports',
						'name' => 'm5_rou_sw_lan',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a1d3272f63',
						'label' => 'LAN max Speed',
						'name' => 'm5_rou_sw_sp',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => '1 GBit/s',
							2 => '100 MBit/s',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'array',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5e9a1db7ebbdf',
						'label' => 'VPN Support',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e9a1dc1ebbe0',
						'label' => 'VPN Client',
						'name' => 'm5_rou_vpn_cli',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'PPTP',
							2 => 'OpenVPN',
							3 => 'L2TP',
							4 => 'Shadowsocks',
							5 => 'Wireguard',
							6 => 'IPsec',
							7 => 'SSH',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a1e3febbe1',
						'label' => 'VPN Server',
						'name' => 'm5_rou_vpn_serv',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'PPTP',
							2 => 'OpenVPN',
							3 => 'L2TP',
							4 => 'Shadowsocks',
							5 => 'Wireguard',
							6 => 'IPsec',
							7 => 'SSH',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a562ae1161',
						'label' => 'KillSwitch',
						'name' => 'm5_rou_vpn_ksw',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.28',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a564de1162',
						'label' => 'Automatic reconnect',
						'name' => 'm5_rou_vpn_au_rc',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.28',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a5675e1163',
						'label' => 'Multiple Client Connections',
						'name' => 'm5_rou_vpn_mcc',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.28',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a569ae1164',
						'label' => 'Max Connectons',
						'name' => 'm5_rou_vpn_max_con',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5e9a5675e1163',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '14.28',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a56dce1165',
						'label' => 'Services Preconfigured',
						'name' => 'm5_rou_vpn_serv_pre',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.28',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a5d51b7f64',
						'label' => 'VPN Statistics',
						'name' => 'm5_rou_vpn_stat',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.28',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a5d7cb7f65',
						'label' => 'TOR/Onion Connection',
						'name' => 'm5_rou_vpn_tor_conn',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.28',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5e9a5c4481eb0',
						'label' => 'VPN-Bypass',
						'name' => 'm5_rou_vpn_bypass',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '35',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Webseite',
							2 => 'IP-adress',
							3 => 'Ports',
							4 => 'Device',
							5 => 'Applications',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a5cad81eb1',
						'label' => 'VPN-Client Control',
						'name' => 'm5_rou_vpn_cli_contr',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '35',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'Browser',
							2 => 'Application',
							3 => 'Browser-Extension',
							4 => 'API-Access',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a5ce281eb2',
						'label' => 'VPN-Client Notifications',
						'name' => 'm5_rou_vpn_cli_notif',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'No',
							2 => 'Push',
							3 => 'EMail',
							4 => 'SMS',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_5e9a5db6b7f66',
						'label' => 'Max Speed tested',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_5e9a60ca77292',
						'label' => 'PPTP',
						'name' => 'm5_rou_vpn_ms_pptp',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a612477293',
						'label' => 'OpenVPN',
						'name' => 'm5_rou_vpn_ms_ovpn',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a613877294',
						'label' => 'L2TP',
						'name' => 'm5_rou_vpn_ms_l2tp',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a614b77295',
						'label' => 'Shadowsocks',
						'name' => 'm5_rou_vpn_ms_shw',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a616b77296',
						'label' => 'Wireguard',
						'name' => 'm5_rou_vpn_ms_wire',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a61ab77297',
						'label' => 'IPsec',
						'name' => 'm5_rou_vpn_ms_ip',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a61ba77298',
						'label' => 'SSH',
						'name' => 'm5_rou_vpn_ms_ssh',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '14.2',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5e9a6778c316c',
						'label' => 'Features',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'top',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5e9a6785c316d',
						'label' => 'Media Server',
						'name' => 'm5_rou_feat_ms',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'File Server',
							2 => 'Print Server',
							3 => 'IPTV Support',
							4 => 'Smart Connect (Wifi)',
							5 => 'Traffic Statistics',
							6 => 'Adaptive QoS',
							7 => 'Wifi Roaming Assistant',
							8 => 'SPI Firewall',
							9 => 'MU-MIMO',
							10 => 'Malwarefilter',
							11 => 'Parental Control',
							12 => 'Download App',
							13 => 'Torrent App',
							14 => 'NAS Features',
							15 => 'Virusfilter',
							16 => 'AdBlocker',
						),
						'allow_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'array',
						'save_custom' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
						array(
							'param' => 'post_category',
							'operator' => '==',
							'value' => 'category:test-bericht',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}
}
new K8AcfRouter();